AWSTemplateFormatVersion: '2010-09-09'
Description: Adjustments service database connections

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
    Description: RDS endpoint address

Resources:
  AdjustmentsPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/adjustments-service/store-password'
      Description: 'Password for adjustments connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\;='''

  AdjustmentsConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/adjustments-service/store-connection'
      Description: 'Connection string for adjustments service store database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_adjustments_service;Password=''${Password}'';Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${AdjustmentsPassword}:SecretString:password}}'

Outputs:
  AdjustmentsConnectionArn:
    Description: ARN of adjustments service store connection secret
    Value: !Ref AdjustmentsConnection
    Export:
      Name: !Sub '${AWS::StackName}-AdjustmentsConnectionArn'
