AWSTemplateFormatVersion: '2010-09-09'
Description: API service database connections

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
    Description: RDS endpoint address

Resources:
  ApiAppPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/app-password'
      Description: 'Password for API app connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\;='''

  ApiAppConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/app-connection'
      Description: 'Connection string for API app database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_api;Password=''${Password}'';Database=Andes_App;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${ApiAppPassword}:SecretString:password}}'

  ApiStoreConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/store-connection'
      Description: 'Connection string for API store database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_api;Password=''${Password}'';Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${ApiAppPassword}:SecretString:password}}'

  ApiSecurityPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/security-password'
      Description: 'Password for API security connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\;='''

  ApiSecurityConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/security-connection'
      Description: 'Connection string for API security database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_api_security;Password=''${Password}'';Database=Andes_App;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${ApiSecurityPassword}:SecretString:password}}'

Outputs:
  ApiStoreConnectionArn:
    Description: ARN of API store connection secret
    Value: !Ref ApiStoreConnection
    Export:
      Name: !Sub '${AWS::StackName}-ApiStoreConnectionArn'

  ApiAppConnectionArn:
    Description: ARN of API app connection secret
    Value: !Ref ApiAppConnection
    Export:
      Name: !Sub '${AWS::StackName}-ApiAppConnectionArn'

  ApiSecurityConnectionArn:
    Description: ARN of API security connection secret
    Value: !Ref ApiSecurityConnection
    Export:
      Name: !Sub '${AWS::StackName}-ApiSecurityConnectionArn'
