AWSTemplateFormatVersion: '2010-09-09'
Description: Load service database connections

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
    Description: RDS endpoint address

Resources:
  LoadStorePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/store-password'
      Description: 'Password for load service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  LoadStoreConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/store-connection'
      Description: 'Connection string for load service store database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_load_service;Password=${Password};Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${LoadStorePassword}:SecretString:password}}'

  LoadAppPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/app-password'
      Description: 'Password for load service app connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  LoadAppConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/app-connection'
      Description: 'Connection string for load service app database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_load_service;Password=${Password};Database=Andes_App;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${LoadAppPassword}:SecretString:password}}'

Outputs:
  LoadStoreConnectionArn:
    Description: ARN of load service store connection secret
    Value: !Ref LoadStoreConnection
    Export:
      Name: !Sub '${AWS::StackName}-LoadStoreConnectionArn'

  LoadAppConnectionArn:
    Description: ARN of load service app connection secret
    Value: !Ref LoadAppConnection
    Export:
      Name: !Sub '${AWS::StackName}-LoadAppConnectionArn'
