AWSTemplateFormatVersion: '2010-09-09'
Description: Murex service database connections

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
    Description: RDS endpoint address

Resources:
  MurexPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/murex-service/store-password'
      Description: 'Password for murex service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  MurexConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/murex-service/store-connection'
      Description: 'Connection string for murex service store database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_murex_service;Password=${Password};Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${MurexPassword}:SecretString:password}}'

Outputs:
  MurexConnectionArn:
    Description: ARN of murex service store connection secret
    Value: !Ref MurexConnection
    Export:
      Name: !Sub '${AWS::StackName}-MurexConnectionArn'
