AWSTemplateFormatVersion: '2010-09-09'
Description: Reporting service database connections

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
    Description: RDS endpoint address

Resources:
  ReportingStorePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/reporting-service/store-password'
      Description: 'Password for reporting service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\;=''{}'''

  ReportingStoreConnection:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/reporting-service/store-connection'
      Description: 'Connection string for reporting service store database'
      SecretString: !Sub 
        - '{"connectionString":"Server=${Endpoint},1433;User Id=andes_login_reporting_service;Password=''${Password}'';Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;"}'
        - Endpoint: !Ref RdsEndpoint
          Password: !Sub '{{resolve:secretsmanager:${ReportingStorePassword}:SecretString:password}}'

Outputs:
  ReportingStoreConnectionArn:
    Description: ARN of reporting service store connection secret
    Value: !Ref ReportingStoreConnection
    Export:
      Name: !Sub '${AWS::StackName}-ReportingStoreConnectionArn'
