AWSTemplateFormatVersion: '2010-09-09'
Description: Database initialization Lambda for Aubrisa Andes

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  RdsEndpoint:
    Type: String
  DbUsername:
    Type: String
  RdsPasswordSecretArn:
    Type: String

Resources:
  DatabaseInitRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref RdsPasswordSecretArn

  DatabaseInitFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AppName}-${EnvironmentName}-db-init'
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt DatabaseInitRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import json
          import boto3
          import pymssql
          import cfnresponse
          
          def handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  # Get DB password from Secrets Manager
                  secrets = boto3.client('secretsmanager')
                  secret = secrets.get_secret_value(SecretId=event['ResourceProperties']['PasswordSecretArn'])
                  password = json.loads(secret['SecretString'])['password']
                  
                  # Connect to SQL Server
                  conn = pymssql.connect(
                      server=event['ResourceProperties']['Endpoint'],
                      user=event['ResourceProperties']['Username'],
                      password=password,
                      database='master'
                  )
                  
                  cursor = conn.cursor()
                  
                  # Create databases
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'Andes_Store') CREATE DATABASE Andes_Store")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'Andes_App') CREATE DATABASE Andes_App")
                  
                  # Create logins
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'andes_login_api') CREATE LOGIN andes_login_api WITH PASSWORD = 'TempPassword123!'")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'andes_login_reporting_service') CREATE LOGIN andes_login_reporting_service WITH PASSWORD = 'TempPassword123!'")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'andes_login_load_service') CREATE LOGIN andes_login_load_service WITH PASSWORD = 'TempPassword123!'")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'andes_login_adjustments') CREATE LOGIN andes_login_adjustments WITH PASSWORD = 'TempPassword123!'")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'andes_login_murex') CREATE LOGIN andes_login_murex WITH PASSWORD = 'TempPassword123!'")
                  
                  # Create users in Andes_Store and grant db_owner
                  cursor.execute("USE Andes_Store")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_api') CREATE USER andes_login_api FOR LOGIN andes_login_api")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_api")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_reporting_service') CREATE USER andes_login_reporting_service FOR LOGIN andes_login_reporting_service")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_reporting_service")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_load_service') CREATE USER andes_login_load_service FOR LOGIN andes_login_load_service")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_load_service")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_adjustments') CREATE USER andes_login_adjustments FOR LOGIN andes_login_adjustments")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_adjustments")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_murex') CREATE USER andes_login_murex FOR LOGIN andes_login_murex")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_murex")
                  
                  # Create users in Andes_App and grant db_owner
                  cursor.execute("USE Andes_App")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_api') CREATE USER andes_login_api FOR LOGIN andes_login_api")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_api")
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'andes_login_load_service') CREATE USER andes_login_load_service FOR LOGIN andes_login_load_service")
                  cursor.execute("ALTER ROLE db_owner ADD MEMBER andes_login_load_service")
                  
                  conn.commit()
                  conn.close()
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})

  DatabaseInit:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt DatabaseInitFunction.Arn
      Endpoint: !Ref RdsEndpoint
      Username: !Ref DbUsername
      PasswordSecretArn: !Ref RdsPasswordSecretArn