AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service for Aubrisa Andes Load Service

Parameters:
  ClusterName:
    Type: String
  DesiredCount:
    Type: Number
  EcsSecurityGroupId:
    Type: String
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  TaskDefArn:
    Type: String

Resources:
  ServiceLoad:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ClusterName}-load'
      Cluster: !Ref ClusterName
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: [!Ref EcsSecurityGroupId]
          Subnets: [!Ref PublicSubnet1Id, !Ref PublicSubnet2Id]
      TaskDefinition: !Ref TaskDefArn


Outputs:
  ServiceName:
    Value: !Ref ServiceLoad
