AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service for Aubrisa Andes Chat API Service

Parameters:
  ClusterName:
    Type: String
  DesiredCount:
    Type: Number
  EcsSecurityGroupId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  TargetGroupArn:
    Type: String
  TaskDefArn:
    Type: String
  ContainerName:
    Type: String
  ContainerPort:
    Type: Number

Resources:
  ServiceChat:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ClusterName}-chat-service'
      Cluster: !Ref ClusterName
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EcsSecurityGroupId]
          Subnets: [!Ref PrivateSubnet1Id, !Ref PrivateSubnet2Id]
      TaskDefinition: !Ref TaskDefArn
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn

Outputs:
  ServiceName:
    Value: !Ref ServiceChat
