AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service for Aubrisa Andes Adjustments Service

Parameters:
  ClusterName:
    Type: String
  DesiredCount:
    Type: Number
  EcsSecurityGroupId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  TaskDefArn:
    Type: String

Resources:
  ServiceAdjustments:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ClusterName}-adjustments-service'
      Cluster: !Ref ClusterName
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EcsSecurityGroupId]
          Subnets: [!Ref PrivateSubnet1Id, !Ref PrivateSubnet2Id]
      TaskDefinition: !Ref TaskDefArn


Outputs:
  ServiceName:
    Value: !Ref ServiceAdjustments
