AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer, listeners, target groups, and rules for Aubrisa Andes

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  AlbSecurityGroupId:
    Type: String
  DomainName:
    Type: String
    Description: FQDN to serve via the ALB (e.g., andes.aubrisa.com)
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID that contains the domain

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-alb'
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref AlbSecurityGroupId

  TgApi:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-api-tg'
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health/live
      Matcher:
        HttpCode: '200,204,301,302'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5

  TgChat:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-chat-tg'
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health/live

  TgUi:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-ui-tg'
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /



  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub '*.${DomainName}'
      ValidationMethod: DNS

  AlbListenerHttp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301



  AlbListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TgUi

  AlbRuleApi:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerHttps
      Priority: 10
      Conditions:
        - Field: host-header
          Values: [!Sub 'api.${DomainName}']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TgApi

  AlbRuleApiOptions:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerHttps
      Priority: 9
      Conditions:
        - Field: host-header
          Values: [!Sub 'api.${DomainName}']
        - Field: http-request-method
          HttpRequestMethodConfig:
            Values: ['OPTIONS']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TgApi

  AlbRuleChat:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerHttps
      Priority: 11
      Conditions:
        - Field: host-header
          Values: [!Sub 'chat-api.${DomainName}']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TgChat



  DnsRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID

  DnsRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID

  DnsRecordWildcard:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '*.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID



Outputs:
  LoadBalancerArn:
    Value: !Ref LoadBalancer
  LoadBalancerDNS:
    Value: !GetAtt LoadBalancer.DNSName
  AlbListenerArn:
    Value: !Ref AlbListenerHttps
  AlbHttpListenerArn:
    Value: !Ref AlbListenerHttp
  TgApiArn:
    Value: !Ref TgApi
  TgChatArn:
    Value: !Ref TgChat
  TgUiArn:
    Value: !Ref TgUi

