#     ___         __         _               ___              __              
#    /   | __  __/ /_  _____(_)________ _   /   |  ____  ____/ /__  _____
#   / /| |/ / / / __ \/ ___/ / ___/ __ `/  / /| | / __ \/ __  / _ \/ ___/
#  / ___ / /_/ / /_/ / /  / (__  ) /_/ /  / ___ |/ / / / /_/ /  __(__  )   
# /_/  |_\__,_/_.___/_/  /_/____/\__,_/  /_/  |_/_/ /_/\__,_/\___/____/  
#
# Copyright (c) 2025 Aubrisa. All rights reserved.
#
# CloudFormation AWS Appplication Deployment

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Aubrisa Andes root stack orchestrating nested stacks for network, storage, IAM, RDS, 
  ALB, ECS tasks, and services

Parameters:
  # Instance Configuration
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  #Entra ID - API key is still a parameter (secret), but TenantId/ClientId moved to SSM
  EntraIdApiKey:
    Type: String
  BotApiKey:
    Type: String
  AiApiKey:
    Type: String
  BotAppType:
    Type: String

  ImageTag:
    Type: String
    Default: latest
  EcrRepositoryUri:
    Type: String
    Description: ECR repository URI base (without tag)

  ExistingVpcId:
    Type: String
    Description: ID of the existing spoke VPC connected to Transit Gateway
  PrivateSubnet1Id:
    Type: String
    Description: ID of the first private subnet in AZ1
  PrivateSubnet2Id:
    Type: String
    Description: ID of the second private subnet in AZ2
  PublicSubnet1Id:
    Type: String
    Description: ID of the first public subnet in AZ1 (for chat ALB)
  PublicSubnet2Id:
    Type: String
    Description: ID of the second public subnet in AZ2 (for chat ALB)
  OnPremCidr:
    Type: String
    Description: CIDR range for on-premises network to access RDS
  DbUsername:
    Type: String
  DbInstanceClass:
    Type: String
    Default: db.m5.large
  DbAllocatedStorage:
    Type: Number
    Default: 100
  DbEngine:
    Type: String
    Default: sqlserver-ex
    AllowedValues: [sqlserver-ex, sqlserver-se, sqlserver-ee]
    Description: SQL Server engine type
  DbEngineVersion:
    Type: String
    Default: '15.00.4322.2.v1'
    Description: SQL Server engine version
  DesiredCount:
    Type: Number
    Default: 1


  BotOAuthConnectionName:
    Type: String
    Default: Azure AD
  AiEndpoint:
    Type: String
  AiChatModelId:
    Type: String
    Default: gpt-4.1
  AiEmbeddingModelId:
    Type: String
    Default: text-embedding-ada-002
  DomainName:
    Type: String
    Description: FQDN served by the internal ALB (e.g., andes.internal.aubrisa.dev)
  ChatDomainName:
    Type: String
    Description: FQDN for the public chat API (e.g., chat-api.aubrisa.dev)
  PrivateHostedZoneId:
    Type: String
    Description: Route 53 private hosted zone ID for internal domain
  PublicHostedZoneId:
    Type: String
    Description: Route 53 public hosted zone ID for chat API domain
  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days
  EnableECSExec:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable ECS Exec for container shell access
  NotificationFromEmailAddress:
    Type: String
  NotificationEnabled:
    Type: String
  NotificationFromName:
    Type: String
  NotificationEmailEnabled:
    Type: String
  NotificationTeamsEnabled:
    Type: String

Resources:
  EntraApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/entraid-api-key'
      Description: 'Entra API key for Andes application'
      SecretString: !Sub '{"key": "${EntraIdApiKey}"}'

  BotApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/bot-api-key'
      Description: 'Bot API key for Andes application'
      SecretString: !Sub '{"key": "${BotApiKey}"}'

  AiApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/ai-api-key'
      Description: 'AI API key for Andes application'
      SecretString: !Sub '{"key": "${AiApiKey}"}'

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: network.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        ExistingVpcId: !Ref ExistingVpcId
        PrivateSubnet1Id: !Ref PrivateSubnet1Id
        PrivateSubnet2Id: !Ref PrivateSubnet2Id
        OnPremCidr: !Ref OnPremCidr

  StorageStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: storage.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        EfsSecurityGroupId: !GetAtt NetworkStack.Outputs.EfsSecurityGroupId
        LogRetentionDays: !Ref LogRetentionDays

  IamStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        SqsQueueArn: !GetAtt StorageStack.Outputs.SqsQueueArn
        EfsFileSystemId: !GetAtt StorageStack.Outputs.EfsFileSystemId

  RdsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: database/rds.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        DbUsername: !Ref DbUsername
        DbInstanceClass: !Ref DbInstanceClass
        DbAllocatedStorage: !Ref DbAllocatedStorage
        DbEngine: !Ref DbEngine
        DbEngineVersion: !Ref DbEngineVersion
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        RdsSecurityGroupId: !GetAtt NetworkStack.Outputs.RdsSecurityGroupId

  # WAF for Chat API
  WafChatStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: public/waf-chat.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        RateLimitPerFiveMinutes: 2000

  # Internal ALB for main services
  AlbStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: alb.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        DomainName: !Ref DomainName
        HostedZoneId: !Ref PrivateHostedZoneId

  # Public ALB for Chat API (Bot Framework)
  AlbChatPublicStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: WafChatStack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: public/alb-chat-public.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1Id: !Ref PublicSubnet1Id
        PublicSubnet2Id: !Ref PublicSubnet2Id
        AlbChatSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbChatSecurityGroupId
        ChatDomainName: !Ref ChatDomainName
        HostedZoneId: !Ref PublicHostedZoneId
        WafWebAclArn: !GetAtt WafChatStack.Outputs.WebAclArn

  EcsTasksStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ecs-tasks.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        ImageTag: !Ref ImageTag
        EcrRepositoryUri: !Ref EcrRepositoryUri
        TaskExecutionRoleArn: !GetAtt IamStack.Outputs.TaskExecutionRoleArn
        ApiTaskRoleArn: !GetAtt IamStack.Outputs.ApiTaskRoleArn
        ChatTaskRoleArn: !GetAtt IamStack.Outputs.ChatTaskRoleArn
        UiTaskRoleArn: !GetAtt IamStack.Outputs.UiTaskRoleArn
        ReportingTaskRoleArn: !GetAtt IamStack.Outputs.ReportingTaskRoleArn
        LoadTaskRoleArn: !GetAtt IamStack.Outputs.LoadTaskRoleArn
        AdjustmentsTaskRoleArn: !GetAtt IamStack.Outputs.AdjustmentsTaskRoleArn
        MurexTaskRoleArn: !GetAtt IamStack.Outputs.MurexTaskRoleArn
        LoadBalancerDNS: !GetAtt AlbStack.Outputs.LoadBalancerDNS
        DomainName: !Ref DomainName
        LogGroupApi: !GetAtt StorageStack.Outputs.LogGroupApi
        LogGroupChat: !GetAtt StorageStack.Outputs.LogGroupChat
        LogGroupUi: !GetAtt StorageStack.Outputs.LogGroupUi
        LogGroupReport: !GetAtt StorageStack.Outputs.LogGroupReport
        LogGroupLoad: !GetAtt StorageStack.Outputs.LogGroupLoad
        LogGroupAdjust: !GetAtt StorageStack.Outputs.LogGroupAdjust
        LogGroupMurex: !GetAtt StorageStack.Outputs.LogGroupMurex
        EfsFileSystemId: !GetAtt StorageStack.Outputs.EfsFileSystemId
        EfsAccessPointId: !GetAtt StorageStack.Outputs.EfsAccessPointId
        BotAppType: !Ref BotAppType
        BotAppIdParameter: !GetAtt StorageStack.Outputs.BotAppIdParameter
        TenantIdParameter: !GetAtt StorageStack.Outputs.TenantIdParameter
        ClientIdParameter: !GetAtt StorageStack.Outputs.ClientIdParameter
        BotTenantIdParameter: !GetAtt StorageStack.Outputs.BotTenantIdParameter
        BotOAuthConnectionName: !Ref BotOAuthConnectionName
        AiEndpoint: !Ref AiEndpoint
        AiChatModelId: !Ref AiChatModelId
        AiEmbeddingModelId: !Ref AiEmbeddingModelId
        EnableECSExec: !Ref EnableECSExec
        NotificationFromEmailAddress: !Ref NotificationFromEmailAddress
        NotificationEnabled: !Ref NotificationEnabled
        NotificationFromName: !Ref NotificationFromName
        NotificationEmailEnabled: !Ref NotificationEmailEnabled
        NotificationTeamsEnabled: !Ref NotificationTeamsEnabled

  EcsServicesStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ecs-services.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        DesiredCount: !Ref DesiredCount
        EcsSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsSecurityGroupId
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
        TgApiArn: !GetAtt AlbStack.Outputs.TgApiArn
        TgChatArn: !GetAtt AlbChatPublicStack.Outputs.TgChatPublicArn
        TgUiArn: !GetAtt AlbStack.Outputs.TgUiArn
        TaskDefApiArn: !GetAtt EcsTasksStack.Outputs.TaskDefApiArn
        TaskDefChatArn: !GetAtt EcsTasksStack.Outputs.TaskDefChatArn
        TaskDefUiArn: !GetAtt EcsTasksStack.Outputs.TaskDefUiArn
        TaskDefReportingArn: !GetAtt EcsTasksStack.Outputs.TaskDefReportingArn
        TaskDefLoadArn: !GetAtt EcsTasksStack.Outputs.TaskDefLoadArn
        TaskDefAdjustmentsArn: !GetAtt EcsTasksStack.Outputs.TaskDefAdjustmentsArn
        TaskDefMurexArn: !GetAtt EcsTasksStack.Outputs.TaskDefMurexArn

Outputs:
  LoadBalancerDNS:
    Value: !GetAtt AlbStack.Outputs.LoadBalancerDNS
    Description: Internal ALB DNS
  ChatApiUrl:
    Value: !GetAtt AlbChatPublicStack.Outputs.ChatApiUrl
    Description: Public chat API URL for Bot Framework configuration
  ChatApiAlbDns:
    Value: !GetAtt AlbChatPublicStack.Outputs.LoadBalancerChatDNS
    Description: Public chat ALB DNS
  QueueUrl:
    Value: !GetAtt StorageStack.Outputs.SqsQueueUrl
  RdsEndpoint:
    Value: !GetAtt RdsStack.Outputs.RdsEndpoint
