#     ___         __         _               ___              __              
#    /   | __  __/ /_  _____(_)________ _   /   |  ____  ____/ /__  _____
#   / /| |/ / / / __ \/ ___/ / ___/ __ `/  / /| | / __ \/ __  / _ \/ ___/
#  / ___ / /_/ / /_/ / /  / (__  ) /_/ /  / ___ |/ / / / /_/ /  __(__  )   
# /_/  |_\__,_/_.___/_/  /_/____/\__,_/  /_/  |_/_/ /_/\__,_/\___/____/  
#
# Copyright (c) 2025 Aubrisa. All rights reserved.
#
# CloudFormation AWS Appplication Deployment

AWSTemplateFormatVersion: '2010-09-09'
Description: Aubrisa Andes root stack orchestrating nested stacks for network, storage, IAM, RDS, ALB, ECS tasks, and services

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  ImageTag:
    Type: String
    Default: latest
  EcrRepositoryUri:
    Type: String
    Default: "221556121332.dkr.ecr.eu-west-2.amazonaws.com"
    Description: ECR repository URI base (without tag)

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  DbUsername:
    Type: String
  DbInstanceClass:
    Type: String
    Default: db.m5.large
  DbAllocatedStorage:
    Type: Number
    Default: 100
  DesiredCount:
    Type: Number
    Default: 1

  BotAppId:
    Type: String
  BotTenantId:
    Type: String
  BotAppType:
    Type: String
  TenantId:
    Type: String
  ClientId:
    Type: String
  BotOAuthConnectionName:
    Type: String
    Default: Azure AD
  AiEndpoint:
    Type: String
  AiChatModelId:
    Type: String
    Default: gpt-4.1
  AiEmbeddingModelId:
    Type: String
    Default: text-embedding-ada-002
  DomainName:
    Type: String
    Description: FQDN served by the ALB (e.g., andes.aubrisa.com)
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID for the domain
  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days
  AdminCidr:
    Type: String
    Description: IP address for admin access to RDS (format x.x.x.x/32)
  EnableECSExec:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable ECS Exec for container shell access
  NotificationFromEmailAddress:
    Type: String
  NotificationEnabled:
    Type: String
  NotificationFromName:
    Type: String
  NotificationEmailEnabled:
    Type: String
  NotificationTeamsEnabled:
    Type: String

Resources:
  EntraApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/entraid-api-key'
      Description: 'Entra API key for Andes application'
      SecretString: '{"key": "PLACEHOLDER_VALUE"}'

  BotApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/bot-api-key'
      Description: 'Bot API key for Andes application'
      SecretString: '{"key": "PLACEHOLDER_VALUE"}'

  AiApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/ai-api-key'
      Description: 'AI API key for Andes application'
      SecretString: '{"key": "PLACEHOLDER_VALUE"}'

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: network.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        AdminCidr: !Ref AdminCidr

  StorageStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: storage.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        EfsSecurityGroupId: !GetAtt NetworkStack.Outputs.EfsSecurityGroupId
        LogRetentionDays: !Ref LogRetentionDays

  IamStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: iam.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        SqsQueueArn: !GetAtt StorageStack.Outputs.SqsQueueArn
        S3BucketArn: !GetAtt StorageStack.Outputs.S3BucketArn

  RdsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        DbUsername: !Ref DbUsername
        DbInstanceClass: !Ref DbInstanceClass
        DbAllocatedStorage: !Ref DbAllocatedStorage
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        RdsSecurityGroupId: !GetAtt NetworkStack.Outputs.RdsSecurityGroupId

  # DatabaseInitStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: RdsStack
  #   Properties:
  #     TemplateURL: ./database/database-init.yaml
  #     Parameters:
  #       AppName: !Ref AppName
  #       EnvironmentName: !Ref EnvironmentName
  #       RdsEndpoint: !GetAtt RdsStack.Outputs.RdsEndpoint
  #       DbUsername: !Ref DbUsername
  #       RdsPasswordSecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/rds-password'

  AlbStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: alb.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId

  EcsTasksStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ecs-tasks.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        ImageTag: !Ref ImageTag
        EcrRepositoryUri: !Ref EcrRepositoryUri
        TaskExecutionRoleArn: !GetAtt IamStack.Outputs.TaskExecutionRoleArn
        ApiTaskRoleArn: !GetAtt IamStack.Outputs.ApiTaskRoleArn
        ChatTaskRoleArn: !GetAtt IamStack.Outputs.ChatTaskRoleArn
        UiTaskRoleArn: !GetAtt IamStack.Outputs.UiTaskRoleArn
        ReportingTaskRoleArn: !GetAtt IamStack.Outputs.ReportingTaskRoleArn
        LoadTaskRoleArn: !GetAtt IamStack.Outputs.LoadTaskRoleArn
        AdjustmentsTaskRoleArn: !GetAtt IamStack.Outputs.AdjustmentsTaskRoleArn
        MurexTaskRoleArn: !GetAtt IamStack.Outputs.MurexTaskRoleArn
        LoadBalancerDNS: !GetAtt AlbStack.Outputs.LoadBalancerDNS
        DomainName: !Ref DomainName
        LogGroupApi: !GetAtt StorageStack.Outputs.LogGroupApi
        LogGroupChat: !GetAtt StorageStack.Outputs.LogGroupChat
        LogGroupUi: !GetAtt StorageStack.Outputs.LogGroupUi
        LogGroupReport: !GetAtt StorageStack.Outputs.LogGroupReport
        LogGroupLoad: !GetAtt StorageStack.Outputs.LogGroupLoad
        LogGroupAdjust: !GetAtt StorageStack.Outputs.LogGroupAdjust
        LogGroupMurex: !GetAtt StorageStack.Outputs.LogGroupMurex
        EfsFileSystemId: !GetAtt StorageStack.Outputs.EfsFileSystemId
        EfsAccessPointId: !GetAtt StorageStack.Outputs.EfsAccessPointId
        BotAppId: !Ref BotAppId
        BotTenantId: !Ref BotTenantId
        BotAppType: !Ref BotAppType
        TenantId: !Ref TenantId
        ClientId: !Ref ClientId
        BotOAuthConnectionName: !Ref BotOAuthConnectionName
        AiEndpoint: !Ref AiEndpoint
        AiChatModelId: !Ref AiChatModelId
        AiEmbeddingModelId: !Ref AiEmbeddingModelId
        EnableECSExec: !Ref EnableECSExec
        NotificationFromEmailAddress: !Ref NotificationFromEmailAddress
        NotificationEnabled: !Ref NotificationEnabled
        NotificationFromName: !Ref NotificationFromName
        NotificationEmailEnabled: !Ref NotificationEmailEnabled
        NotificationTeamsEnabled: !Ref NotificationTeamsEnabled

  EcsServicesStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ecs-services.yaml
      Parameters:
        AppName: !Ref AppName
        EnvironmentName: !Ref EnvironmentName
        DesiredCount: !Ref DesiredCount
        EcsSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsSecurityGroupId
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        TgApiArn: !GetAtt AlbStack.Outputs.TgApiArn
        TgChatArn: !GetAtt AlbStack.Outputs.TgChatArn
        TgUiArn: !GetAtt AlbStack.Outputs.TgUiArn
        TaskDefApiArn: !GetAtt EcsTasksStack.Outputs.TaskDefApiArn
        TaskDefChatArn: !GetAtt EcsTasksStack.Outputs.TaskDefChatArn
        TaskDefUiArn: !GetAtt EcsTasksStack.Outputs.TaskDefUiArn
        TaskDefReportingArn: !GetAtt EcsTasksStack.Outputs.TaskDefReportingArn
        TaskDefLoadArn: !GetAtt EcsTasksStack.Outputs.TaskDefLoadArn
        TaskDefAdjustmentsArn: !GetAtt EcsTasksStack.Outputs.TaskDefAdjustmentsArn
        TaskDefMurexArn: !GetAtt EcsTasksStack.Outputs.TaskDefMurexArn

Outputs:
  LoadBalancerDNS:
    Value: !GetAtt AlbStack.Outputs.LoadBalancerDNS
  QueueUrl:
    Value: !GetAtt StorageStack.Outputs.SqsQueueUrl
  RdsEndpoint:
    Value: !GetAtt RdsStack.Outputs.RdsEndpoint
