AWSTemplateFormatVersion: '2010-09-09'
Description: RDS SQL Server instance for Aubrisa Andes Store/App Databases

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  DbUsername:
    Type: String
  DbInstanceClass:
    Type: String
  DbAllocatedStorage:
    Type: Number
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  RdsSecurityGroupId:
    Type: String
  DbEngine:
    Type: String
    Default: sqlserver-ex
    AllowedValues: [sqlserver-ex, sqlserver-se, sqlserver-ee]
    Description: SQL Server engine type
  DbEngineVersion:
    Type: String
    Default: '15.00.4322.2.v1'
    Description: SQL Server engine version

Resources:
  RdsPasswordSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/rds-password'
      Description: 'RDS password for Andes database'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${AppName}-${EnvironmentName}-rds-subnet-group'
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id

  RdsInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub '${AppName}-${EnvironmentName}-sql'
      Engine: !Ref DbEngine
      EngineVersion: !Ref DbEngineVersion
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RdsPasswordSecret}:SecretString:password}}'
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref DbAllocatedStorage
      StorageEncrypted: true
      StorageType: gp3
      MultiAZ: false
      VPCSecurityGroups:
        - !Ref RdsSecurityGroupId
      DBSubnetGroupName: !Ref DbSubnetGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 7
      LicenseModel: license-included

  ApiStorePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/store-password'
      Description: 'Password for API store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  ApiStoreConnection:
    Type: AWS::SSM::Parameter
    DependsOn: ApiStorePassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-store-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_api;Password=TempPassword123!;Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;'

  ApiAppPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/app-password'
      Description: 'Password for API app connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  ApiAppConnection:
    Type: AWS::SSM::Parameter
    DependsOn: ApiAppPassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-app-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_api;Password=TempPassword123!;Database=Andes_App;Encrypt=true;TrustServerCertificate=true;'

  ApiSecurityPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/api/security-password'
      Description: 'Password for API security connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  ApiSecurityConnection:
    Type: AWS::SSM::Parameter
    DependsOn: ApiAppPassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-security-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_api_security;Password=TempPassword123!;Database=Andes_App;Encrypt=true;TrustServerCertificate=true;'

  ReportingStorePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/reporting-service/store-password'
      Description: 'Password for reporting service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  ReportingStoreConnection:
    Type: AWS::SSM::Parameter
    DependsOn: ReportingStorePassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-reporting-store-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_reporting_service;Password=TempPassword123!;Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;'

  LoadStorePassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/store-password'
      Description: 'Password for load service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  LoadStoreConnection:
    Type: AWS::SSM::Parameter
    DependsOn: LoadStorePassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-load-store-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_load_service;Password=TempPassword123!;Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;'

  LoadAppPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/load-service/app-password'
      Description: 'Password for load service app connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  LoadAppConnection:
    Type: AWS::SSM::Parameter
    DependsOn: LoadAppPassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-load-app-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_load_service;Password=TempPassword123!;Database=Andes_App;Encrypt=true;TrustServerCertificate=true;'

  AdjustmentsPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/reporting-service/adjustments-password'
      Description: 'Password for adjustments connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  AdjustmentsConnection:
    Type: AWS::SSM::Parameter
    DependsOn: AdjustmentsPassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-adjustments-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_adjustments_service;Password=TempPassword123!;Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;'

  MurexPassword:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub '${AppName}/${EnvironmentName}/murex-service/store-password'
      Description: 'Password for murex service store connection'
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  MurexConnection:
    Type: AWS::SSM::Parameter
    DependsOn: MurexPassword
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-murex-connection'
      Type: String
      Value: !Sub 'Server=${RdsInstance.Endpoint.Address},1433;User Id=andes_login_murex_service;Password=TempPassword123!;Database=Andes_Store;Encrypt=true;TrustServerCertificate=true;'

Outputs:
  RdsEndpoint:
    Value: !GetAtt RdsInstance.Endpoint.Address
