AWSTemplateFormatVersion: '2010-09-09'
Description: Adjustments Task Role for Aubrisa Andes

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String

Resources:
  AdjustmentsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AdjustmentsSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${EnvironmentName}/reporting-service/adjustments-connection'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sqs:SetQueueAttributes
                  - sqs:ReceiveMessage
                  - sqs:CreateQueue
                  - sqs:DeleteMessage
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                  - sqs:PurgeQueue
                  - sqs:DeleteQueue
                  - sqs:TagQueue
                Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - sns:GetTopicAttributes
                  - sns:ListSubscriptionsByTopic
                  - sns:GetSubscriptionAttributes
                  - sns:SetSubscriptionAttributes
                  - sns:CreateTopic
                  - sns:Publish
                  - sns:Subscribe
                Resource: !Sub 'arn:aws:sns:*:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - sns:ListTopics
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: '*'

Outputs:
  AdjustmentsTaskRoleArn:
    Value: !GetAtt AdjustmentsTaskRole.Arn