AWSTemplateFormatVersion: '2010-09-09'
Description: Adjustments Task Role for Aubrisa Andes

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String

Resources:
  AdjustmentsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AdjustmentsServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/adjustments-service/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/andes/${EnvironmentName}/adjustments*'
              - Effect: Allow
                Action:
                  - sqs:SetQueueAttributes
                  - sqs:ReceiveMessage
                  - sqs:CreateQueue
                  - sqs:DeleteMessage
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                  - sqs:PurgeQueue
                  - sqs:DeleteQueue
                  - sqs:TagQueue
                Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${AppName}-${EnvironmentName}*'
              - Effect: Allow
                Action:
                  - sns:GetTopicAttributes
                  - sns:ListSubscriptionsByTopic
                  - sns:GetSubscriptionAttributes
                  - sns:SetSubscriptionAttributes
                  - sns:CreateTopic
                  - sns:Publish
                  - sns:Subscribe
                Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${AppName}-${EnvironmentName}*'
              - Effect: Allow
                Action:
                  - sns:ListTopics
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: '*'

Outputs:
  AdjustmentsTaskRoleArn:
    Value: !GetAtt AdjustmentsTaskRole.Arn