AWSTemplateFormatVersion: '2010-09-09'
Description: Adjustments Task Role for Aubrisa Andes

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String

Resources:
  AdjustmentsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AdjustmentsSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${EnvironmentName}/reporting-service/adjustments-connection'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  AdjustmentsTaskRoleArn:
    Value: !GetAtt AdjustmentsTaskRole.Arn