AWSTemplateFormatVersion: '2010-09-09'
Description: UI Task Role for Aubrisa Andes

Parameters:
  EnvironmentName:
    Type: String

Resources:
  UiTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: UiPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/andes/${EnvironmentName}/ui*'

Outputs:
  UiTaskRoleArn:
    Value: !GetAtt UiTaskRole.Arn