AWSTemplateFormatVersion: '2010-09-09'
Description: Public-facing Application Load Balancer for Chat API with Microsoft Bot Framework access

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet1Id:
    Type: String
    Description: First public subnet for ALB
  PublicSubnet2Id:
    Type: String
    Description: Second public subnet for ALB
  AlbChatSecurityGroupId:
    Type: String
  ChatDomainName:
    Type: String
    Description: FQDN for the chat API (e.g., chat-api.aubrisa.com)
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID for the domain
  WafWebAclArn:
    Type: String
    Description: ARN of the WAF Web ACL to associate with the ALB
    Default: ''

Conditions:
  HasWafWebAcl: !Not [!Equals [!Ref WafWebAclArn, '']]

Resources:
  LoadBalancerChat:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-chat-alb'
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref AlbChatSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-${EnvironmentName}-chat-alb'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Service
          Value: Chat

  WafAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Condition: HasWafWebAcl
    Properties:
      ResourceArn: !Ref LoadBalancerChat
      WebACLArn: !Ref WafWebAclArn

  TgChat:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${EnvironmentName}-chat-public-tg'
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: /health/live
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-${EnvironmentName}-chat-public-tg'

  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ChatDomainName
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-${EnvironmentName}-chat-cert'

  AlbListenerHttp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancerChat
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  AlbListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancerChat
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificate
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TgChat

  DnsRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ChatDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancerChat.DNSName
        HostedZoneId: !GetAtt LoadBalancerChat.CanonicalHostedZoneID
        EvaluateTargetHealth: true

  DnsRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ChatDomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt LoadBalancerChat.DNSName
        HostedZoneId: !GetAtt LoadBalancerChat.CanonicalHostedZoneID
        EvaluateTargetHealth: true

Outputs:
  LoadBalancerChatArn:
    Value: !Ref LoadBalancerChat
    Description: ARN of the public chat ALB
  LoadBalancerChatDNS:
    Value: !GetAtt LoadBalancerChat.DNSName
    Description: DNS name of the public chat ALB
  TgChatPublicArn:
    Value: !Ref TgChat
    Description: ARN of the chat target group
  AlbListenerHttpsArn:
    Value: !Ref AlbListenerHttps
    Description: ARN of the HTTPS listener
  ChatApiUrl:
    Value: !Sub 'https://${ChatDomainName}'
    Description: Public URL for the chat API (use this in Bot Framework configuration)
