AWSTemplateFormatVersion: '2010-09-09'
Description: ECS TaskDefinition for Aubrisa Andes Chat API Service

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  ImageTag:
    Type: String
  EcrRepositoryUri:
    Type: String
  TaskExecutionRoleArn:
    Type: String
  TaskRoleArn:
    Type: String
  LogGroupChat:
    Type: String
  BotAppId:
    Type: String
  BotTenantId:
    Type: String
  BotAppType:
    Type: String
  BotOAuthConnectionName:
    Type: String
  AiEndpoint:
    Type: String
  AiChatModelId:
    Type: String
  AiEmbeddingModelId:
    Type: String

Resources:
  TaskDefChat:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-chat'
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: chat
          Image: !Sub '${EcrRepositoryUri}/aubrisa/andes-chat-api:aws-${ImageTag}'
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: ASPNETCORE_ENVIRONMENT
              Value: !Ref EnvironmentName
            - Name: AWSSETTINGS__REGION
              Value: !Ref AWS::Region
            - Name: CHATSETTINGS__BOTAPPTYPE
              Value: !Ref BotAppType
            - Name: CHATSETTINGS__BOTAPPID
              Value: !Ref BotAppId
            - Name: CHATSETTINGS__BOTTENANTID
              Value: !Ref BotTenantId
            - Name: CHATSETTINGS__AUTHENTICATIONCONFIGNAME
              Value: !Ref BotOAuthConnectionName
            - Name: CHATSETTINGS__AIENDPOINT
              Value: !Ref AiEndpoint
            - Name: CHATSETTINGS__CHATMODELID
              Value: !Ref AiChatModelId
            - Name: CHATSETTINGS__EMBEDDINGMODELID
              Value: !Ref AiEmbeddingModelId
          Secrets:
            - Name: CHATSETTINGS__BOTAPPKEY
              ValueFrom: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}-${EnvironmentName}/bot-api-key'
            - Name: CHATSETTINGS__AIAPIKEY
              ValueFrom: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}-${EnvironmentName}/ai-api-key'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupChat
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: chat

Outputs:
  TaskDefChatArn:
    Value: !Ref TaskDefChat
