AWSTemplateFormatVersion: '2010-09-09'
Description: ECS TaskDefinition for Aubrisa Andes API

Parameters:
  AppName:
    Type: String
  EnvironmentName:
    Type: String
  TenantId:
    Type: String
  ClientId:
    Type: String
  BotAppId:
    Type: String
  BotTenantId:
    Type: String
  BotAppType:
    Type: String
  BotOAuthConnectionName:
    Type: String
  ImageTag:
    Type: String
  EcrRepositoryUri:
    Type: String
  TaskExecutionRoleArn:
    Type: String
  TaskRoleArn:
    Type: String
  DomainName:
    Type: String
  LogGroupApi:
    Type: String
  EfsFileSystemId:
    Type: String
  EfsAccessPointId:
    Type: String
  AiEndpoint:
    Type: String
  AiChatModelId:
    Type: String
  AiEmbeddingModelId:
    Type: String
  EnableECSExec:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable ECS Exec for container shell access
  NotificationFromEmailAddress:
    Type: String
  NotificationEnabled:
    Type: String
  NotificationFromName:
    Type: String
  NotificationEmailEnabled:
    Type: String
  NotificationTeamsEnabled:
    Type: String

Conditions:
  EmailEnabled: !Equals [!Ref NotificationEmailEnabled, "true"]
  TeamsEnabled: !Equals [!Ref NotificationTeamsEnabled, "true"]

Resources:
  TaskDefApi:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-api'
      Cpu: '8192'
      Memory: '32768'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: api
          Image: !Sub '${EcrRepositoryUri}/aubrisa/andes-api:aws-${ImageTag}'
          PortMappings:
            - ContainerPort: 8080
          LinuxParameters:
            InitProcessEnabled: !Ref EnableECSExec
          Environment:
            - Name: ASPNETCORE_ENVIRONMENT
              Value: !Ref EnvironmentName
            - Name: ENTRAID__TENANTID
              Value: !Ref TenantId
            - Name: ENTRAID__CLIENTID
              Value: !Ref ClientId
            - Name: AWSSETTINGS__REGION
              Value: !Ref AWS::Region
            - Name: AWSSETTINGS__MESSAGEDATAPATH
              Value: /mnt/shared/load-messages
            - Name: REPORTSETTINGS__REPORTPATH
              Value: /mnt/shared/reports
            - Name: LOADSETTINGS__LOADSPATH
              Value: /mnt/shared/load-definitions
            - Name: LOADSETTINGS__DATAPATH
              Value: /mnt/shared/load-data
            - Name: AISETTINGS__AIENDPOINT
              Value: !Ref AiEndpoint
            - Name: AISETTINGS__CHATMODELID
              Value: !Ref AiChatModelId
            - Name: AISETTINGS__EMBEDDINGMODELID
              Value: !Ref AiEmbeddingModelId
            - Name: NOTIFICATIONSETTINGS__BOTAPPTYPE
              Value: !Ref BotAppType
            - Name: NOTIFICATIONSETTINGS__BOTAPPID
              Value: !Ref BotAppId
            - Name: NOTIFICATIONSETTINGS__BOTTENANTID
              Value: !Ref BotTenantId
            - Name: NOTIFICATIONSETTINGS__AUTHENTICATIONCONFIGNAME
              Value: !Ref BotOAuthConnectionName
            - Name: UI_BASE_URL
              Value: !Sub 'https://${DomainName}'
            - Name: LiveCorsOrigins
              Value: !Sub 'https://${DomainName},https://api.${DomainName},https://chat-api.${DomainName}'
            - Name: NOTIFICATIONSETTINGS__FROMEMAILADDRESS
              Value: !Ref NotificationFromEmailAddress
            - Name: NOTIFICATIONSETTINGS__ISENABLED
              Value: !Ref NotificationEnabled
            - Name: NOTIFICATIONSETTINGS__FROMNAME
              Value: !Ref NotificationFromName
            - Name: NOTIFICATIONSETTINGS__CHANNELS__0
              Value: !If [EmailEnabled, "Email", ""]
            - Name: NOTIFICATIONSETTINGS__CHANNELS__1
              Value: !If [TeamsEnabled, "Teams", ""]
          Secrets:
            - Name: ENTRAID__APISECRET
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/entraid-api-key:key::'
            - Name: AISETTINGS__AIAPIKEY
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/ai-api-key:key::'
            - Name: NOTIFICATIONSETTINGS__BOTAPPKEY
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/bot-api-key:key::'
            - Name: ConnectionStrings__StoreConnectionString
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/api/store-connection:connectionString::'
            - Name: ConnectionStrings__AppConnectionString
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/api/app-connection:connectionString::'
            - Name: ConnectionStrings__SecurityConnectionString
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${EnvironmentName}/api/security-connection:connectionString::'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupApi
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: api
          MountPoints:
            - ContainerPath: /mnt/shared
              SourceVolume: shared-files

      Volumes:
        - Name: shared-files
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsFileSystemId
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId

Outputs:
  TaskDefApiArn:
    Value: !Ref TaskDefApi
